import { Colors } from "@/constants/theme";
import { StyleSheet } from "react-native";

const applicationSheet = StyleSheet.create({
    textView:{
        backgroundColor:'#F3F4F6',
        padding:20,
        borderRadius:4
    },
    detailView:{
        flexDirection:'row',
        padding:20,
        justifyContent:'space-between',
        alignItems:'center',
        borderColor:'#C6C6CD'        
    },
    detailLeft:{
        flexDirection:'row',
        alignItems:'center',
    },
    detailMiddle:{
        borderBottomWidth:1
    },
    details:{
        borderWidth:1,
        borderColor:'#C6C6CD',
        borderRadius:8,
        marginVertical:20
    },
    inputView:{
        flexDirection:'row',
        alignItems:'center',
        borderWidth:1,
        borderColor:'#C6C6CD',
        padding:10,
        borderRadius:4,
        marginVertical:5
    },
    line:{
        height:2,
        borderRadius:5,
        marginLeft:5,
        backgroundColor:'#AFC3EE',
        flex:1
    },
    resumeView:{
        flexDirection:'row',
        padding:20,
        justifyContent:'space-between',
        alignItems:'center',
        borderWidth:1,
        borderColor:Colors.primary,
        borderRadius:12,
        marginVertical:10 
    },
    resumeView2:{
        borderWidth:1,
        borderColor:'#F5F5F5',
        borderRadius:8,
        alignItems:'center',
        padding:30
    },
    browseButton:{
        paddingVertical:8,
        paddingHorizontal:15,
        borderRadius:5,
        borderWidth:1,
        borderColor:Colors.primary,
        marginTop:30
    },
    buttons:{
        flexDirection:'row',
        alignItems:'center'
    },
    sentTop:{
        alignItems:'center',
        padding:24
    }
});
export default applicationSheet