import { Colors } from "@/constants/theme";
import { StyleSheet } from "react-native";

const homeSheet = StyleSheet.create({
    profilePic:{
        width:26,
        height:26,
        borderRadius:50,
        marginLeft:10
    },
    top:{
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'flex-end',
        paddingHorizontal:20,
        paddingVertical:10
    },
    topRight:{
        flexDirection:'row',
        alignItems:'center'
    },
    searchView:{
        flexDirection:'row',
        borderWidth:1,
        borderColor:'#D4D4D4',
        borderRadius:12,
        height:55,
        flex:1,
    },
    input:{
        color:'#5E5F61',
    },
    filter:{
        width:50,
        height:50
    },
    row:{
        flexDirection:'row',
        alignItems:'center',
    },
    bannerView:{
        flexDirection:'row',
    },
    banner:{
        backgroundColor:Colors.primary,
        padding:20,
        height:260,
        borderRadius:12,
        width:280,
        justifyContent:'space-between',
        margin:10
    },
    bannerIconView:{
        backgroundColor:'#FFFFFF1A',
        width:48,
        height:48,
        borderRadius:8,
        alignItems:'center',
        justifyContent:'center',
    },
    typeView:{
        backgroundColor:'#FFFFFF1A',
        paddingVertical:2,
        borderRadius:100,
        alignSelf:'flex-start',
        paddingHorizontal:8,
        borderWidth:1,
        borderColor:'#FFFFFF33',
        marginTop:10
    },
    card:{
        padding:16,
        borderWidth:1,
        borderColor: Colors.primary,
        borderRadius:12,
        marginVertical:10
    },
    cardImage:{
        width:48,
        height:48,
        marginRight:10
    },
    cardTop:{
        flexDirection:'row',
        justifyContent:'space-between'
    },
    tag:{
        backgroundColor:'#C8DBEF',
        paddingVertical:2,
        borderRadius:100,
        alignSelf:'flex-start',
        paddingHorizontal:8,
        margin:3
    },
    tags:{
        flexDirection:'row',
        flexWrap:'wrap',
        marginTop:8
    }
});

export default homeSheet